@extends('master')
@section('content')

 <div class="container">
 <div class="row justify-content-left ">
<p></p>


	 <div class="k_cheading">
		<h1>ISUW 2021 <span class="k_greencolor">Participating Utilities </span> </h1>
		<img src="/public/uploads/images/kborder_bottom.png" alt=""> 
	</div>
<p></p>
<!--<div class="col-lg-3"><div class="logo-div"><a href="http://www.recpdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/pdcllogo.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://posoco.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/POSOCO_Final_Logo.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dvvnl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/Dakshinanchal-Vidyut-Vitran-Nigam-Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apeasternpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/APEPDCL.png" alt="" height="125" /> </a></div></div>
-->
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tssouthernpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/Southern-Power-Distribution-Company-of-Telangana-State-Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.indiapower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/INDIA-POWER.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apspdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/APSPDCL.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://energy.rajasthan.gov.in/avvnl" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  style="" src="http://www.isuw.in/beta/wp-content/uploads/2020/02/Ajmer-Vidyut-Vitran-Nigam-Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.ugvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/beta/wp-content/uploads/2020/02/Uttar-Gujarat-Vij-Company-Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://bescom.co.in/SCP/Myhome.aspx" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/1641223586.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.bsesdelhi.com/web/bypl#loaded" target="_blank" rel="noopener noreferrer"><img style="margin: 0 auto; height: 44px; margin-top: 27px;" src="https://www.isuw.in/public/uploads/utility/1641110101.png" alt=""></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.bsesdelhi.com/web/brpl" target="_blank" rel="noopener noreferrer"><img style="margin: 0 auto; height: 50px; width: 151px; margin-top: 23px;" src="https://www.isuw.in/public/uploads/utility/1641110129.png" alt=""></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.cesc.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/1641223726.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.noidapower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/1641486892.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.tatapower-ddl.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.isuw.in/public/uploads/utility/1641110211.png" alt="" width="213" height="102"></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tatapower.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.isuw.in/public/uploads/utility/1641110147.png" style="margin-top:-10px;"></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tsecl.in/irj/go/km/docs/internet/TRIPURA/webpage/pages/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/wp-content/uploads/2021/02/Tripura.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://cescmysore.karnataka.gov.in/english" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Chamudeshwari Electricity Supply Company Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.cspdcl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Chhattisgarh State Power Distribution Co. Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://dhbvn.org.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/DHBVN_Logo.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Dakshin Gujarat Vij Co Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.guvnl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Gujarat Urja Vikas Nigam Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.hpseb.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Himachal Pradesh State Electricity Board.gif" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://hescom.karnataka.gov.in/english" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Hubli Electricity Supply Co. Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.jkspdc.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/J&K.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://energy.rajasthan.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Jaipur Vidyut Vitran Nigam Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/JdVVNLa.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://jbvnl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Jharkhand Bijli Vitran Nigam Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://kseb.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Kerala State Electricity Board Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Madhya Gujarat Vij. Co. Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.mpwz.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Madhya Pradesh Pachim Kshetra Vidyut Vitran Co Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.mvvnl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Madhyanchal Vidyut Vitran Nigam Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://mspcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Manipur State Power Distribution Company Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://meecl.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Meghalaya Power Distribution Corporation Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mescom.org.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/MESCOM.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mahadiscom.in/en/home/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/MSEDCL.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://nbpdcl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/North Bihar Power Distribution Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.ntpc.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/NTPC.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.pgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Paschim Gujarat Vij Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://pvvnl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Paschimanchal Vidyut Vitran Nigam Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://pspcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/PSPCL-English-Logo.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://puvvnl.up.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Purvanchal Vidyut Vitran Nigam Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apspdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/South Bihar Power Distribution Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tangedco.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Tamil Nadu Electricity Board.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.torrentpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/Torrent Power Ltd.png" alt="" height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.tpcentralodisha.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/TPCODL.jpg" alt="" height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.uhbvn.org.in/web/portal/home" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/UHBVN.png" alt="" height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.wbsedcl.in/irj/go/km/docs/internet/new_website/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/West Bengal State Electricity Dist. Co. Ltd.png" alt=""  /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://tsnpdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isuw.in/public/uploads/utility/The Northern Power Distribution Company of Telangana Limited(TSNPDCL).png" alt="" height="43" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.adanielectricity.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isuw.in/public/uploads/partner/Adani Electricity Mumbai Ltd.png" alt="" /> </a></div></div>


<p></p>
</div>
</div>

@endsection